server:
  port: 9000

spring:
  application:
    name: api-gateway

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#对某一个服务修改访问名称
zuul:
  routes:
    order-service:/apigateway/product/**
    product-service:/apigateway/order/**
#  统一为上面的URL访问，不能下面的方式访问
  ignored-patterns: - /*-service/**
#                    处理http请求头为null
  sensitive-headers: :
#  ignored-services: product-service